theme: jekyll-theme-hacker
# Allow future dated posts
future: true
title: JMES Crypto Castle
url: "https://cryptocastle.tech" # the base hostname & protocol for your site
repoBaseUrl: https://github.com/crypto-castle/castle-website 
plugins:
  - jekyll-sitemap
tagline: Get rewards for helping to build JMES
description: Claim bounties for new ideas, specifying and working on tasks, and carring out QA on JMES blockchain software.
logo: /assets/image/logo.svg
twitter:
  username: cryptocastle
  card: summary
social:
  name: JMES Crypto Casle
  links:
    - https://twitter.com/cryptocastle
    - https://github.com/cryptocastle
    - https://chat.cryptocastle.tech
google_analytics: G-PZE9FSBKDS
