theme: jekyll-theme-hacker
# Allow future dated posts
future: true
title: JMES Crypto Castle
url: "https://cryptocastle.tech" # the base hostname & protocol for your site
repoBaseUrl: https://github.com/crypto-castle/incubator-website 
plugins:
  - jekyll-sitemap
tagline: Get rewards for helping to build Dash
description: Claim bounties for new ideas, specifying and working on tasks, and carring out QA on JMES blockchain software.
logo: /assets/image/incubator-logo.jpg
twitter:
  username: dashincubator
  card: summary
social:
  name: Dash Incubator
  links:
    - https://twitter.com/dashincubator
    - https://github.com/cryptocastle
    - https://chat.dashdevs.org
google_analytics: G-PZE9FSBKDS
